### ISSUE TITLE
multiple TX-RX CSI setup

### ISSUE THREAD

**Issue by yujianyuanhaha** [StevenMHernandez/ESP32-CSI-Tool#17]
greetings,

how can we setup multiple TX-RX CSI, based on the page,  I guess we can do 1AP-multipleStations setup, so there are multiple TX-RX setup. What is the commands for establishing the AP-station links? How can we sync these stations?

Best

Jet

**Comment by StevenMHernandez** [comment]
When configuring the esp32s (https://github.com/StevenMHernandez/ESP32-CSI-Tool#configuration-esp-idf) the `ESP32 CSI Tool Config > ****` configuration options will allow you to set each STA to connect to a single AP. Make sure both STAs are flashed with the same SSID/Password so that they can connect to the same AP.

We want more help to make the multi-TX/RX system more robust! Any additional help is always appreciated!
